version: '3'

services:
  devops-toolkit:
    image: devops_toolkit
    ports:
      - "2230:22"
    volumes:
      # - ~/Desktop/Dev/terraform_modules/tf-module-aws-vpc:/home/user/tf-module-aws-vpc
      - ./:/home/user/tf-module
      - ./key:/home/user/key
      - ~/.aws:/root/.aws
    container_name: tf-module-vpc_cn
    restart: unless-stopped
