version: '3'

services:
  ansible_terraform:
    image: ansible_terraform
    ports:
      - "2223:22"
    volumes:
      # - ~/Desktop/Dev/terraform_modules/tf-module-aws-vpc:/home/user/tf-module-aws-vpc
      - ./:/home/user/tf-module
      - ~/Desktop/Dev/key:/home/user/key
      - ~/.aws:/home/user/.aws
    container_name: tf-module-vpc
    restart: unless-stopped
